// print("---------------test Queue Array---------------")
// var queue = QueueArray<String>()
// queue.enqueue("Ray")
// queue.enqueue("Brian")
// queue.enqueue("Eric")
// print(queue)
// queue.dequeue()
// print(queue)


print("---------------test Queue LinkedList---------------")
var queue = QueueLinkedList<String>()
queue.enqueue("Ray")
queue.enqueue("Brian")
queue.enqueue("Eric")
print(queue)
queue.dequeue()
print(queue)
